services:
  server1:
    build: .
    container_name: server1
    command: ["./servidor", "5500"]
    networks:
      - app-net

  server2:
    build: .
    container_name: server2
    command: ["./servidor", "5500"]
    networks:
      - app-net

  server3:
    build: .
    container_name: server3
    command: ["./servidor", "5500"]
    networks:
      - app-net

  server4:
    build: .
    container_name: server4
    command: ["./servidor", "5500"]
    networks:
      - app-net
  
  client1:
    build: .
    container_name: client1
    command: ["./cliente", "5500" , "< ./tests/RAND_NUM_1.txt"]
    networks:
      - app-net
    stdin_open: true

  client2:
    build: .
    container_name: client2
    command: ["./cliente", "5500"]
    networks:
      - app-net
    stdin_open: true

  client3:
    build: .
    container_name: client3
    command: ["./cliente", "5500"]
    networks:
      - app-net
    stdin_open: true    

networks:
  app-net:
    driver: bridge