version: '3.8'

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  server:
    image: server_client
    container_name: server
    command: ["server"]
    hostname: server
    networks:
      my_network:
        ipv4_address: 192.168.1.100
    entrypoint: ["/bin/sh", "-c", "./server_client server"]

  client1:
    image: server_client
    container_name: client1
    hostname: client1
    networks:
      my_network:
        ipv4_address: 192.168.1.101
    volumes:
      - ./src/RAND_NUM_1.txt:/app/src/RAND_NUM_1.txt:ro
    entrypoint: ["/bin/sh", "-c", "cat /app/src/RAND_NUM_1.txt | ./server_client client"]

  client2:
    image: server_client
    container_name: client2
    hostname: client2
    networks:
      my_network:
        ipv4_address: 192.168.1.102
    volumes:
      - ./src/RAND_NUM_2.txt:/app/src/RAND_NUM_2.txt:ro
    entrypoint: ["/bin/sh", "-c", "cat /app/src/RAND_NUM_2.txt | ./server_client client"]

  client3:
    image: server_client
    container_name: client3
    hostname: client3
    networks:
      my_network:
        ipv4_address: 192.168.1.103
    volumes:
      - ./src/RAND_NUM_3.txt:/app/src/RAND_NUM_3.txt:ro
    entrypoint: ["/bin/sh", "-c", "cat /app/src/RAND_NUM_3.txt | ./server_client client"]